config/routes.rb
Smartvalue::Application.routes.draw do
  resources :companies

  root 'companies#index'
end

app/models/company.rb
class Company < ActiveRecord::Base

  def dcf_intrinsic_value
    discount_rate = 0.08

    present_value_of_future_cash_flows = 0
    for year in (0..10)
      present_value_of_future_cash_flows += self.cash_flow_per_share*1.05 / (1 + discount_rate)**year
    end

    return self.cash_per_share + present_value_of_future_cash_flows
  end

  def discount
    discount = ( (self.stock_price - self.dcf_intrinsic_value) / self.dcf_intrinsic_value )*100
    return discount
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :symbol, :market, :stock_price, :cash_per_share, :cash_flow_per_share)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :market %><br>
    <%= f.text_field :market %>
  </div>
  <div class="field">
    <%= f.label :stock_price %><br>
    <%= f.text_field :stock_price %>
  </div>
  <div class="field">
    <%= f.label :cash_per_share %><br>
    <%= f.number_field :cash_per_share %>
  </div>
  <div class="field">
    <%= f.label :cash_flow_per_share %><br>
    <%= f.number_field :cash_flow_per_share %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h2>Companies</h2>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Symbol</th>
      <th>Market</th>
      <th>Stock Price</th>
      <th>Cash per share</th>
      <th>Cash flow per share</th>
      <th>Intrinsic value (DCF)</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><span class="company_name"><%= link_to company.name, company %></span></td>
        <td><%= company.symbol %></td>
        <td><%= company.market %></td>
        <td><%= number_to_currency(company.stock_price.to_f / 100) %></td>
        <td><%= number_to_currency(company.cash_per_share.to_f / 100) %></td>
        <td><%= number_to_currency(company.cash_flow_per_share.to_f / 100) %></td>
        <td><%= number_to_currency(company.dcf_intrinsic_value.to_f / 100) %></td>
        <td>
          <% if company.discount > 10 %>
            <span class="label label-danger">sell</span>
          <% elsif company.discount < -10 %>
            <span class="label label-success">buy</span>
          <% else %>
            <span class="label label-info">meh</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><%= @company.name %><br><small><%= @company.market %> : <%= @company.symbol %></small></h1>
</div>

<div class="row">

  <div class="col-md-4">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Stock Price</h3>
      </div>
      <div class="panel-body">
        <%= number_to_currency(@company.stock_price.to_f / 100) %>
      </div>
    </div>

  </div>

  <div class="col-md-4">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Intrinsic value (DCF)</h3>
      </div>
      <div class="panel-body">
        <%= number_to_currency(@company.dcf_intrinsic_value.to_f / 100) %>
      </div>
    </div>

  </div>

  <div class="col-md-4">

    <% if @company.discount > 10 %>

      <div class="panel panel-danger valued overvalued">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-exclamation-triangle"></i> overvalued</h3>
        </div>
        <div class="panel-body">
          <%= number_to_percentage(@company.discount, precision: 0) %>
        </div>
      </div>

    <% elsif @company.discount < -10 %>

      <div class="panel panel-success valued undervalued">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-thumbs-o-up"></i> undervalued</h3>
        </div>
        <div class="panel-body">
          <%= number_to_percentage(@company.discount.abs, precision: 0) %>
        </div>
      </div>

    <% else %>

      <div class="panel panel-info valued fairly_valued">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-hand-o-right"></i></i> fairly valued</h3>
        </div>
        <div class="panel-body">
          <%= number_to_percentage(@company.discount, precision: 0) %>
        </div>
      </div>
    <% end %>

  </div>

</div>

<hr>

<div class="row">
  <div class="col-md-12">
    <p><strong>cash per share:</strong> <%= number_to_currency(@company.cash_per_share.to_f / 100) %></p>
    <p><strong>cash flow per share:</strong> <%= number_to_currency(@company.cash_flow_per_share.to_f / 100) %></p>
  </div>
</div>

<hr>

<%= link_to 'Edit', edit_company_path(@company), class: "btn btn-warning" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartvalue</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SmartValue</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<!--         <ul class="nav navbar-nav">
          <li><a href="/companies">Companies</a></li>
        </ul> -->
<!--         <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form> -->
        <ul class="nav navbar-nav navbar-right">
          <!-- <li><a href="#">About</a></li> -->
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>

    <div class="container">

      <p class="text-muted"><em>Stock prices: last close 12/12/2013</em></p>

      <%= yield %>
    </div>

  </body>
</html>